name: deeppocket
channels:
  - defaults
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.8
  - numpy=1.21
  - matplotlib=3.5
  - scikit-learn=1.0
  - rdkit=2021.09.5
  - pytorch=1.10.2
  - torchvision=0.11.3
  - pip
  - pip:
      - wandb==0.17.0
      - biopython==1.79
      - molgrid==0.5.3
      - prody==2.4.1
